using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.OrmLite.Attributes
{
    /// <summary>
    /// Represents a database populated field
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class AutoGeneratedAttribute : Attribute
    {
    }
}
