/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: khannan
 * Date: 2017-4-16
 */

using OpenIZ.OrmLite;
using OpenIZ.OrmLite.Attributes;
using System;

namespace OpenIZ.Persistence.Reporting.PSQL.Model
{
	/// <summary>
	/// Represents identified data.
	/// </summary>
	/// <seealso cref="OpenIZ.OrmLite.IAdoLoadedData" />
	/// <seealso cref="IDbIdentified" />
	public abstract class DbIdentified : IAdoLoadedData, IDbIdentified
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DbIdentified"/> class.
		/// </summary>
		/// <param name="key">The key.</param>
		protected DbIdentified(Guid key)
		{
			this.Key = key;
		}

		/// <summary>
		/// Gets the data context
		/// </summary>
		/// <value>The context.</value>
		public DataContext Context { get; set; }

		/// <summary>
		/// Gets or sets the key.
		/// </summary>
		/// <value>The key.</value>
		[AutoGenerated]
		public abstract Guid Key { get; set; }
	}
}