/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: khannan
 * Date: 2017-4-4
 */

using OpenIZ.OrmLite.Attributes;
using System;

namespace OpenIZ.Persistence.Reporting.PSQL.Model
{
	/// <summary>
	/// Represents a report format.
	/// </summary>
	[Table("report_format")]
	public class ReportFormat : DbIdentified
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ReportFormat"/> class.
		/// </summary>
		public ReportFormat() : this(Guid.NewGuid())
		{
			this.CreationTime = DateTimeOffset.UtcNow;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ReportFormat"/> class.
		/// </summary>
		/// <param name="key">The key.</param>
		public ReportFormat(Guid key) : base(key)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ReportFormat"/> class
		/// with a specific report format name.
		/// </summary>
		/// <param name="name">The name of the report format.</param>
		public ReportFormat(string name) : this()
		{
			this.Name = name;
		}

		/// <summary>
		/// Gets or sets the creation time of the report format.
		/// </summary>
		[NotNull]
		[Column("creation_time")]
		public DateTimeOffset CreationTime { get; set; }

		/// <summary>
		/// Gets or sets the key.
		/// </summary>
		/// <value>The key.</value>
		[PrimaryKey]
		[Column("id")]
		[AutoGenerated]
		public override Guid Key { get; set; }

		/// <summary>
		/// Gets or sets the name of the report format.
		/// </summary>
		[NotNull]
		[Column("name")]
		public string Name { get; set; }
	}
}