/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: khannan
 * Date: 2017-4-4
 */

using OpenIZ.OrmLite.Attributes;
using System;

namespace OpenIZ.Persistence.Reporting.PSQL.Model
{
	/// <summary>
	/// Represents a report definition.
	/// </summary>
	[Table("report_definition")]
	public class ReportDefinition : DbIdentified
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ReportDefinition"/> class.
		/// </summary>
		public ReportDefinition() : base(Guid.NewGuid())
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ReportDefinition"/> class.
		/// </summary>
		/// <param name="key">The key.</param>
		public ReportDefinition(Guid key) : base(key)
		{
			this.CreationTime = DateTimeOffset.UtcNow;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ReportDefinition"/> class
		/// with a specific <see cref="Core.Model.RISI.ReportDefinition"/> instance.
		/// </summary>
		/// <param name="report">The report instance.</param>
		public ReportDefinition(Core.Model.RISI.ReportDefinition report) : this(report.Key.Value)
		{
			this.Author = report.CreatedBy.UserName;
			this.CorrelationId = report.CorrelationId;
			this.Description = report.Description;
			this.Name = report.Name;
		}

		/// <summary>
		/// Gets or sets the author of the report.
		/// </summary>
		[NotNull]
		[Column("author")]
		public string Author { get; set; }

		/// <summary>
		/// Gets or sets the correlation id of the report.
		/// </summary>
		[NotNull]
		[Column("correlation_id")]
		public string CorrelationId { get; set; }

		/// <summary>
		/// Gets or sets the creation time of the report.
		/// </summary>
		[NotNull]
		[Column("creation_time")]
		public DateTimeOffset CreationTime { get; set; }

		/// <summary>
		/// Gets or sets the description of the report.
		/// </summary>
		[Column("description")]
		public string Description { get; set; }

		/// <summary>
		/// Gets or sets the key.
		/// </summary>
		/// <value>The key.</value>
		[PrimaryKey]
		[Column("id")]
		[AutoGenerated]
		public override Guid Key { get; set; }

		/// <summary>
		/// Gets or sets the name of the report.
		/// </summary>
		[NotNull]
		[Column("name")]
		public string Name { get; set; }
	}
}