/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justi
 * Date: 2017-1-14
 */
using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Persistence.Data.ADO.Data.Model.Acts
{
    /// <summary>
    /// Table which stores clinical protocols
    /// </summary>
    [Table("proto_tbl")]
    public class DbProtocol : DbBaseData
    {
        /// <summary>
        /// Gets or sets the protocol id
        /// </summary>
        [Column("proto_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        [Column("proto_name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the handler identifier
        /// </summary>
        [Column("hdlr_id"), ForeignKey(typeof(DbProtocolHandler), nameof(DbProtocolHandler.Key)), AlwaysJoin]
        public Guid HandlerKey { get; set; }

        /// <summary>
        /// Gets or sets the OID
        /// </summary>
        [Column("oid")]
        public String Oid { get; set; }

        /// <summary>
        /// Definition of the protocol
        /// </summary>
        [Column("defn")]
        public byte[] Definition { get; set; }

        /// <summary>
        /// Gets or sets the replaces key if applicable
        /// </summary>
        [Column("rplc_proto_id")]
        public Guid? ReplacesProtocolKey { get; set; }
    }

    /// <summary>
    /// Represents a protocol handler
    /// </summary>
    [Table("proto_hdlr_tbl")]
    public class DbProtocolHandler : DbBaseData
    {
        /// <summary>
        /// Gets or sets the primary key
        /// </summary>
        [Column("hdlr_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the handler name
        /// </summary>
        [Column("hdlr_name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the handler class
        /// </summary>
        [Column("hdlr_cls")]
        public String TypeName { get; set; }

        /// <summary>
        /// Gets or sets whether the protocol is active
        /// </summary>
        [Column("is_active")]
        public bool IsActive { get; set; }

    }
}
