using OpenIZ.Persistence.Data.ADO.Data.Attributes;
using System;
using System.Reflection;

namespace OpenIZ.Persistence.Data.ADO.Util
{
    /// <summary>
    /// Column mapping
    /// </summary>
    public class ColumnMapping
    {

        /// <summary>
        /// Gets the source property
        /// </summary>
        public PropertyInfo SourceProperty { get; private set; }

        /// <summary>
        /// Gets the name of the column
        /// </summary>
        public String Name { get; private set; }

        /// <summary>
        /// True if column is primary key
        /// </summary>
        public bool IsPrimaryKey { get; private set; }

        /// <summary>
        /// True if column is set by database
        /// </summary>
        public bool IsAutoGenerated { get; private set; }

        /// <summary>
        /// Create a column mapping
        /// </summary>
        private ColumnMapping(PropertyInfo pi)
        {
            this.Name = pi.GetCustomAttribute<ColumnAttribute>()?.Name ?? pi.Name;
            this.IsPrimaryKey = pi.GetCustomAttribute<PrimaryKeyAttribute>() != null;
            this.IsAutoGenerated = pi.GetCustomAttribute<AutoGeneratedAttribute>() != null;
            this.SourceProperty = pi;
        }

        /// <summary>
        /// Get property mapping
        /// </summary>
        public static ColumnMapping Get(PropertyInfo pi)
        {
            return new ColumnMapping(pi);
        }
    }
}