/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justi
 * Date: 2017-1-14
 */
using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Persistence.Data.ADO.Data.Model.DataType
{

    /// <summary>
    /// Phonetic value table
    /// </summary>
    [Table("phon_val_tbl")]
    public class DbPhoneticValue : DbIdentified
    {

        /// <summary>
        /// Gets or sets the value
        /// </summary>
        [Column("val")]
        public String Value { get; set; }

        /// <summary>
        /// Gets or sets the phonetic code.
        /// </summary>
        /// <value>The phonetic code.</value>
        [Column("phon_cs")]
        public String PhoneticCode
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the phonetic algorithm identifier.
        /// </summary>
        /// <value>The phonetic algorithm identifier.</value>
        [Column("alg_id"), ForeignKey(typeof(DbPhoneticAlgorithm), nameof(DbPhoneticAlgorithm.Key))]
        public Guid PhoneticAlgorithmKey
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the key of the phonetic code
        /// </summary>
        [Column("val_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Sequence identifier
        /// </summary>
        [Column("val_seq_id"), AutoGenerated]
        public Decimal? SequenceId { get; set; }
    }

    /// <summary>
    /// Represents a phonetic algorithm
    /// </summary>
    [Table("phon_alg_tbl")]
    public class DbPhoneticAlgorithm : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the algorithm key
        /// </summary>
        [Column("alg_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the algorithm name
        /// </summary>
        [Column("alg_name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the handler class
        /// </summary>
        [Column("hdlr_cls")]
        public String HandlerClass { get; set; }
    }
}
