using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Warehouse.ADO.Data.Model
{
    /// <summary>
    /// Represents an adhoc property
    /// </summary>
    [Table("adhoc_sch_props")]
    public class AdhocProperty
    {

        /// <summary>
        /// Gets or sets the property
        /// </summary>
        [Column("uuid"), NotNull, AutoGenerated]
        public Guid PropertyId { get; set; }

        /// <summary>
        /// Container identifier
        /// </summary>
        [Column("cont_uuid"), ForeignKey(typeof(AdhocProperty), nameof(AdhocProperty.PropertyId))]
        public Guid? ContainerId { get; set; }

        /// <summary>
        /// Schema identifier
        /// </summary>
        [Column("sch_uuid"), NotNull, ForeignKey(typeof(AdhocSchema), nameof(AdhocSchema.SchemaId))]
        public Guid SchemaId { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Type identifier
        /// </summary>
        [Column("type"), NotNull]
        public int TypeId { get; set; }

        /// <summary>
        /// Attributes
        /// </summary>
        [Column("attr"), NotNull]
        public int Attributes { get; set; }


    }
}
