using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Warehouse.ADO.Data.Model
{
    /// <summary>
    /// Adhoc schema
    /// </summary>
    [Table("adhoc_sch")]
    public class AdhocSchema
    {

        /// <summary>
        /// UUID column
        /// </summary>
        [Column("uuid"), NotNull, AutoGenerated]
        public Guid SchemaId { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }
    }
}
