using OpenIZ.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenIZ.Warehouse.ADO.Data.Model
{
    /// <summary>
    /// Adhoc query
    /// </summary>
    [Table("adhoc_query")]
    public class AdhocQuery
    {

        /// <summary>
        /// Gets or sets the query identifier
        /// </summary>
        [Column("uuid"), NotNull, AutoGenerated]
        public Guid QueryId { get; set; }

        /// <summary>
        /// Gets or sets the schema identifier
        /// </summary>
        [Column("sch_uuid"), NotNull, ForeignKey(typeof(AdhocSchema), nameof(AdhocSchema.SchemaId))]
        public Guid SchemaId { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }
    }
}
