/*
 * Copyright 2015-2017 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justi
 * Date: 2017-4-8
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


namespace OizDevTool
{


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ihe:iti:csd:2013", IsNullable = false)]
	public partial class CSD
	{

		private organization[] organizationDirectoryField;

		private service[] serviceDirectoryField;

		private facility[] facilityDirectoryField;

		private provider[] providerDirectoryField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public organization[] organizationDirectory
		{
			get
			{
				return this.organizationDirectoryField;
			}
			set
			{
				this.organizationDirectoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public service[] serviceDirectory
		{
			get
			{
				return this.serviceDirectoryField;
			}
			set
			{
				this.serviceDirectoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public facility[] facilityDirectory
		{
			get
			{
				return this.facilityDirectoryField;
			}
			set
			{
				this.facilityDirectoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
		public provider[] providerDirectory
		{
			get
			{
				return this.providerDirectoryField;
			}
			set
			{
				this.providerDirectoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class organization : uniqueID
	{

		private otherID[] otherIDField;

		private codedtype[] codedTypeField;

		private string primaryNameField;

		private organizationOtherName[] otherNameField;

		private address[] addressField;

		private organizationContact[] contactField;

		private credential[] credentialField;

		private codedtype[] languageField;

		private codedtype[] specializationField;

		private contactPoint[] contactPointField;

		private uniqueID parentField;

		private extension[] extensionField;

		private record recordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherID")]
		public otherID[] otherID
		{
			get
			{
				return this.otherIDField;
			}
			set
			{
				this.otherIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("codedType")]
		public codedtype[] codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		public string primaryName
		{
			get
			{
				return this.primaryNameField;
			}
			set
			{
				this.primaryNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherName")]
		public organizationOtherName[] otherName
		{
			get
			{
				return this.otherNameField;
			}
			set
			{
				this.otherNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("address")]
		public address[] address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contact")]
		public organizationContact[] contact
		{
			get
			{
				return this.contactField;
			}
			set
			{
				this.contactField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("credential")]
		public credential[] credential
		{
			get
			{
				return this.credentialField;
			}
			set
			{
				this.credentialField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("language")]
		public codedtype[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("specialization")]
		public codedtype[] specialization
		{
			get
			{
				return this.specializationField;
			}
			set
			{
				this.specializationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contactPoint")]
		public contactPoint[] contactPoint
		{
			get
			{
				return this.contactPointField;
			}
			set
			{
				this.contactPointField = value;
			}
		}

		/// <remarks/>
		public uniqueID parent
		{
			get
			{
				return this.parentField;
			}
			set
			{
				this.parentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		public record record
		{
			get
			{
				return this.recordField;
			}
			set
			{
				this.recordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class otherID
	{

		private string codeField;

		private string assigningAuthorityNameField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string code
		{
			get
			{
				return this.codeField;
			}
			set
			{
				this.codeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string assigningAuthorityName
		{
			get
			{
				return this.assigningAuthorityNameField;
			}
			set
			{
				this.assigningAuthorityNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class operatingHours
	{

		private bool openFlagField;

		private string[] dayOfTheWeekField;

		private System.DateTime beginningHourField;

		private bool beginningHourFieldSpecified;

		private System.DateTime endingHourField;

		private bool endingHourFieldSpecified;

		private System.DateTime beginEffectiveDateField;

		private System.DateTime endEffectiveDateField;

		private bool endEffectiveDateFieldSpecified;

		/// <remarks/>
		public bool openFlag
		{
			get
			{
				return this.openFlagField;
			}
			set
			{
				this.openFlagField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("dayOfTheWeek", DataType = "integer")]
		public string[] dayOfTheWeek
		{
			get
			{
				return this.dayOfTheWeekField;
			}
			set
			{
				this.dayOfTheWeekField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
		public System.DateTime beginningHour
		{
			get
			{
				return this.beginningHourField;
			}
			set
			{
				this.beginningHourField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool beginningHourSpecified
		{
			get
			{
				return this.beginningHourFieldSpecified;
			}
			set
			{
				this.beginningHourFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
		public System.DateTime endingHour
		{
			get
			{
				return this.endingHourField;
			}
			set
			{
				this.endingHourField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endingHourSpecified
		{
			get
			{
				return this.endingHourFieldSpecified;
			}
			set
			{
				this.endingHourFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime beginEffectiveDate
		{
			get
			{
				return this.beginEffectiveDateField;
			}
			set
			{
				this.beginEffectiveDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime endEffectiveDate
		{
			get
			{
				return this.endEffectiveDateField;
			}
			set
			{
				this.endEffectiveDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endEffectiveDateSpecified
		{
			get
			{
				return this.endEffectiveDateFieldSpecified;
			}
			set
			{
				this.endEffectiveDateFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class geocode
	{

		private decimal latitudeField;

		private decimal longitudeField;

		private decimal altitudeField;

		private bool altitudeFieldSpecified;

		private string coordinateSystemField;

		/// <remarks/>
		public decimal latitude
		{
			get
			{
				return this.latitudeField;
			}
			set
			{
				this.latitudeField = value;
			}
		}

		/// <remarks/>
		public decimal longitude
		{
			get
			{
				return this.longitudeField;
			}
			set
			{
				this.longitudeField = value;
			}
		}

		/// <remarks/>
		public decimal altitude
		{
			get
			{
				return this.altitudeField;
			}
			set
			{
				this.altitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool altitudeSpecified
		{
			get
			{
				return this.altitudeFieldSpecified;
			}
			set
			{
				this.altitudeFieldSpecified = value;
			}
		}

		/// <remarks/>
		public string coordinateSystem
		{
			get
			{
				return this.coordinateSystemField;
			}
			set
			{
				this.coordinateSystemField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class record
	{

		private System.DateTime createdField;

		private System.DateTime updatedField;

		private string statusField;

		private string sourceDirectoryField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime created
		{
			get
			{
				return this.createdField;
			}
			set
			{
				this.createdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime updated
		{
			get
			{
				return this.updatedField;
			}
			set
			{
				this.updatedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string status
		{
			get
			{
				return this.statusField;
			}
			set
			{
				this.statusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
		public string sourceDirectory
		{
			get
			{
				return this.sourceDirectoryField;
			}
			set
			{
				this.sourceDirectoryField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class extension
	{

		private System.Xml.XmlElement anyField;

		private string typeField;

		private string urnField;

		private System.Xml.XmlAttribute[] anyAttrField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement Any
		{
			get
			{
				return this.anyField;
			}
			set
			{
				this.anyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string urn
		{
			get
			{
				return this.urnField;
			}
			set
			{
				this.urnField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyAttributeAttribute()]
		public System.Xml.XmlAttribute[] AnyAttr
		{
			get
			{
				return this.anyAttrField;
			}
			set
			{
				this.anyAttrField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class credential
	{

		private codedtype codedTypeField;

		private string numberField;

		private string issuingAuthorityField;

		private System.DateTime credentialIssueDateField;

		private bool credentialIssueDateFieldSpecified;

		private System.DateTime credentialRenewalDateField;

		private bool credentialRenewalDateFieldSpecified;

		private extension[] extensionField;

		/// <remarks/>
		public codedtype codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		public string number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		public string issuingAuthority
		{
			get
			{
				return this.issuingAuthorityField;
			}
			set
			{
				this.issuingAuthorityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime credentialIssueDate
		{
			get
			{
				return this.credentialIssueDateField;
			}
			set
			{
				this.credentialIssueDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool credentialIssueDateSpecified
		{
			get
			{
				return this.credentialIssueDateFieldSpecified;
			}
			set
			{
				this.credentialIssueDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime credentialRenewalDate
		{
			get
			{
				return this.credentialRenewalDateField;
			}
			set
			{
				this.credentialRenewalDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool credentialRenewalDateSpecified
		{
			get
			{
				return this.credentialRenewalDateFieldSpecified;
			}
			set
			{
				this.credentialRenewalDateFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class codedtype
	{

		private string codeField;

		private string codingSchemeField;

		private System.Xml.XmlAttribute[] anyAttrField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string code
		{
			get
			{
				return this.codeField;
			}
			set
			{
				this.codeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string codingScheme
		{
			get
			{
				return this.codingSchemeField;
			}
			set
			{
				this.codingSchemeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyAttributeAttribute()]
		public System.Xml.XmlAttribute[] AnyAttr
		{
			get
			{
				return this.anyAttrField;
			}
			set
			{
				this.anyAttrField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class contactPoint
	{

		private codedtype codedTypeField;

		private string equipmentField;

		private string purposeField;

		private string certificateField;

		/// <remarks/>
		public codedtype codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		public string equipment
		{
			get
			{
				return this.equipmentField;
			}
			set
			{
				this.equipmentField = value;
			}
		}

		/// <remarks/>
		public string purpose
		{
			get
			{
				return this.purposeField;
			}
			set
			{
				this.purposeField = value;
			}
		}

		/// <remarks/>
		public string certificate
		{
			get
			{
				return this.certificateField;
			}
			set
			{
				this.certificateField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class name
	{

		private nameCommonName[] commonNameField;

		private string honorificField;

		private string forenameField;

		private codedtype[] otherNameField;

		private string surnameField;

		private string suffixField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("commonName")]
		public nameCommonName[] commonName
		{
			get
			{
				return this.commonNameField;
			}
			set
			{
				this.commonNameField = value;
			}
		}

		/// <remarks/>
		public string honorific
		{
			get
			{
				return this.honorificField;
			}
			set
			{
				this.honorificField = value;
			}
		}

		/// <remarks/>
		public string forename
		{
			get
			{
				return this.forenameField;
			}
			set
			{
				this.forenameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherName")]
		public codedtype[] otherName
		{
			get
			{
				return this.otherNameField;
			}
			set
			{
				this.otherNameField = value;
			}
		}

		/// <remarks/>
		public string surname
		{
			get
			{
				return this.surnameField;
			}
			set
			{
				this.surnameField = value;
			}
		}

		/// <remarks/>
		public string suffix
		{
			get
			{
				return this.suffixField;
			}
			set
			{
				this.suffixField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class nameCommonName
	{

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class person
	{

		private personName[] nameField;

		private contactPoint[] contactPointField;

		private address[] addressField;

		private string genderField;

		private System.DateTime dateOfBirthField;

		private bool dateOfBirthFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public personName[] name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contactPoint")]
		public contactPoint[] contactPoint
		{
			get
			{
				return this.contactPointField;
			}
			set
			{
				this.contactPointField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("address")]
		public address[] address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <remarks/>
		public string gender
		{
			get
			{
				return this.genderField;
			}
			set
			{
				this.genderField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime dateOfBirth
		{
			get
			{
				return this.dateOfBirthField;
			}
			set
			{
				this.dateOfBirthField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dateOfBirthSpecified
		{
			get
			{
				return this.dateOfBirthFieldSpecified;
			}
			set
			{
				this.dateOfBirthFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class personName : name
	{

		private string langField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class address
	{

		private addressAddressLine[] addressLineField;

		private string typeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("addressLine")]
		public addressAddressLine[] addressLine
		{
			get
			{
				return this.addressLineField;
			}
			set
			{
				this.addressLineField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class addressAddressLine
	{

		private string componentField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string component
		{
			get
			{
				return this.componentField;
			}
			set
			{
				this.componentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(service))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(provider))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(facility))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(organization))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class uniqueID
	{

		private string entityIDField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string entityID
		{
			get
			{
				return this.entityIDField;
			}
			set
			{
				this.entityIDField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class service : uniqueID
	{

		private otherID[] otherIDField;

		private codedtype[] codedTypeField;

		private extension[] extensionField;

		private record recordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherID")]
		public otherID[] otherID
		{
			get
			{
				return this.otherIDField;
			}
			set
			{
				this.otherIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("codedType")]
		public codedtype[] codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		public record record
		{
			get
			{
				return this.recordField;
			}
			set
			{
				this.recordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class provider : uniqueID
	{

		private otherID[] otherIDField;

		private codedtype[] codedTypeField;

		private person demographicField;

		private codedtype[] languageField;

		private providerOrganization[] organizationsField;

		private providerFacility[] facilitiesField;

		private credential[] credentialField;

		private codedtype[] specialtyField;

		private extension[] extensionField;

		private record recordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherID")]
		public otherID[] otherID
		{
			get
			{
				return this.otherIDField;
			}
			set
			{
				this.otherIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("codedType")]
		public codedtype[] codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		public person demographic
		{
			get
			{
				return this.demographicField;
			}
			set
			{
				this.demographicField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("language")]
		public codedtype[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("organization", IsNullable = false)]
		public providerOrganization[] organizations
		{
			get
			{
				return this.organizationsField;
			}
			set
			{
				this.organizationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("facility", IsNullable = false)]
		public providerFacility[] facilities
		{
			get
			{
				return this.facilitiesField;
			}
			set
			{
				this.facilitiesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("credential")]
		public credential[] credential
		{
			get
			{
				return this.credentialField;
			}
			set
			{
				this.credentialField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("specialty")]
		public codedtype[] specialty
		{
			get
			{
				return this.specialtyField;
			}
			set
			{
				this.specialtyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		public record record
		{
			get
			{
				return this.recordField;
			}
			set
			{
				this.recordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class providerOrganization : uniqueID
	{

		private extension[] extensionField;

		private address[] addressField;

		private contactPoint[] contactPointField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("address")]
		public address[] address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contactPoint")]
		public contactPoint[] contactPoint
		{
			get
			{
				return this.contactPointField;
			}
			set
			{
				this.contactPointField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class providerFacility : uniqueID
	{

		private providerFacilityService[] serviceField;

		private operatingHours[] operatingHoursField;

		private extension[] extensionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("service")]
		public providerFacilityService[] service
		{
			get
			{
				return this.serviceField;
			}
			set
			{
				this.serviceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("operatingHours")]
		public operatingHours[] operatingHours
		{
			get
			{
				return this.operatingHoursField;
			}
			set
			{
				this.operatingHoursField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class providerFacilityService : uniqueID
	{

		private name[] nameField;

		private uniqueID organizationField;

		private codedtype[] languageField;

		private operatingHours[] operatingHoursField;

		private string freeBusyURIField;

		private extension[] extensionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public uniqueID organization
		{
			get
			{
				return this.organizationField;
			}
			set
			{
				this.organizationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("language")]
		public codedtype[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("operatingHours")]
		public operatingHours[] operatingHours
		{
			get
			{
				return this.operatingHoursField;
			}
			set
			{
				this.operatingHoursField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
		public string freeBusyURI
		{
			get
			{
				return this.freeBusyURIField;
			}
			set
			{
				this.freeBusyURIField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:csd:2013")]
	public partial class facility : uniqueID
	{

		private otherID[] otherIDField;

		private codedtype[] codedTypeField;

		private string primaryNameField;

		private facilityOtherName[] otherNameField;

		private address[] addressField;

		private facilityContact[] contactField;

		private geocode geocodeField;

		private codedtype[] languageField;

		private contactPoint[] contactPointField;

		private uniqueID parentField;

		private facilityOrganization[] organizationsField;

		private operatingHours[] operatingHoursField;

		private extension[] extensionField;

		private record recordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherID")]
		public otherID[] otherID
		{
			get
			{
				return this.otherIDField;
			}
			set
			{
				this.otherIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("codedType")]
		public codedtype[] codedType
		{
			get
			{
				return this.codedTypeField;
			}
			set
			{
				this.codedTypeField = value;
			}
		}

		/// <remarks/>
		public string primaryName
		{
			get
			{
				return this.primaryNameField;
			}
			set
			{
				this.primaryNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("otherName")]
		public facilityOtherName[] otherName
		{
			get
			{
				return this.otherNameField;
			}
			set
			{
				this.otherNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("address")]
		public address[] address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contact")]
		public facilityContact[] contact
		{
			get
			{
				return this.contactField;
			}
			set
			{
				this.contactField = value;
			}
		}

		/// <remarks/>
		public geocode geocode
		{
			get
			{
				return this.geocodeField;
			}
			set
			{
				this.geocodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("language")]
		public codedtype[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("contactPoint")]
		public contactPoint[] contactPoint
		{
			get
			{
				return this.contactPointField;
			}
			set
			{
				this.contactPointField = value;
			}
		}

		public uniqueID parent
		{
			get
			{
				return this.parentField;
			}
			set
			{
				this.parentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("organization", IsNullable = false)]
		public facilityOrganization[] organizations
		{
			get
			{
				return this.organizationsField;
			}
			set
			{
				this.organizationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("operatingHours")]
		public operatingHours[] operatingHours
		{
			get
			{
				return this.operatingHoursField;
			}
			set
			{
				this.operatingHoursField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}

		/// <remarks/>
		public record record
		{
			get
			{
				return this.recordField;
			}
			set
			{
				this.recordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class facilityOtherName
	{

		private string langField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class facilityContact
	{

		private object itemField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("person", typeof(person))]
		[System.Xml.Serialization.XmlElementAttribute("provider", typeof(uniqueID))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class facilityOrganization : uniqueID
	{

		private facilityOrganizationService[] serviceField;

		private extension[] extensionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("service")]
		public facilityOrganizationService[] service
		{
			get
			{
				return this.serviceField;
			}
			set
			{
				this.serviceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class facilityOrganizationService : uniqueID
	{

		private name[] nameField;

		private codedtype[] languageField;

		private operatingHours[] operatingHoursField;

		private string freeBusyURIField;

		private extension[] extensionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("name")]
		public name[] name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("language")]
		public codedtype[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("operatingHours")]
		public operatingHours[] operatingHours
		{
			get
			{
				return this.operatingHoursField;
			}
			set
			{
				this.operatingHoursField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
		public string freeBusyURI
		{
			get
			{
				return this.freeBusyURIField;
			}
			set
			{
				this.freeBusyURIField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("extension")]
		public extension[] extension
		{
			get
			{
				return this.extensionField;
			}
			set
			{
				this.extensionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class organizationOtherName
	{

		private string langField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ihe:iti:csd:2013")]
	public partial class organizationContact
	{

		private object itemField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("person", typeof(person))]
		[System.Xml.Serialization.XmlElementAttribute("provider", typeof(uniqueID))]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

}